// @flow
export const KEY_SELECTION_RECENT = 'KEY_SELECTION_RECENT';
export const KEY_SELECTION_SEARCH = 'KEY_SELECTION_SEARCH';
export const KEY_SELECTION_DOWNLOADED = 'KEY_SELECTION_DOWNLOADED';

export type KeySelection = 'KEY_SELECTION_RECENT' | 'KEY_SELECTION_SEARCH' | 'KEY_SELECTION_DOWNLOADED';
